language: python

before_install:
    - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
    - bash Miniconda3-latest-Linux-x86_64.sh -b
    - . /home/travis/miniconda3/etc/profile.d/conda.sh
    - conda update --yes conda
    - conda config --add channels r
    - conda create --yes -n test
    - conda activate test
    - conda install -y pycodestyle
    - conda install --yes python=3.6
    - conda install --yes numpy
    - conda install --yes matplotlib
    - conda install --yes pycodestyle
    - git submodule update --init
      
script:

    - python -m unittest test_data_viz.py
    - python -m unittest hash-tables-tlfobe/test_hash_tables.py
    - pycodestyle *.py